### ISSUE TITLE
Quick outline view appears with a collapsed tree

### ISSUE THREAD

**Issue by aykutkilic** [LorenzoBettini/xsemantics#40] opened 2014-10-10 13:58 UTC
Quick Outline view (CTRL+O) appears with a collapsed tree. 

The tree structure is as below:
![image](https://cloud.githubusercontent.com/assets/1406590/4593349/3989811e-5085-11e4-8d76-e4eb7300fd44.png)

```
expressions-first --> selects whole document
  <unnamed>  --> selects imports section
  it.xsemantics.example.expressions.typing.ExpressionsSemantics --> system element
    list of judgments, rules, ...
```
Imo simplifying the list to a flat list of judgments, rules, axioms would make it better.

**Comment by LorenzoBettini** [comment] 2015-02-11 16:09
The quick outline now shows a 1 level expanded tree with all the judgments and auxiliary descriptions (corresponding rules are now children of the judgment nodes).

![xsemantics_outline](https://cloud.githubusercontent.com/assets/1202254/6150618/975a0984-b210-11e4-977e-72f4912a11ac.png)

I think this closes this issue.

Please feel free to reopen it if it's not the intended behavior.

This will be part of the next release

**Closed by LorenzoBettini** 2015-02-11 16:09 UTC

**Comment by aykutkilic** [comment] 2015-02-11 20:23
That's it. Thanks.

On Wed, Feb 11, 2015 at 5:09 PM, LorenzoBettini <notifications@github.com>
wrote:

> Closed #40 <https://github.com/LorenzoBettini/xsemantics/issues/40>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LorenzoBettini/xsemantics/issues/40#event-234026531>.
>



-- 
AykutK.

**Comment by LorenzoBettini** [comment] 2015-02-12 10:32
version 1.7.1 has been released with this fix

**Comment by aykutkilic** [comment] 2015-02-12 10:56
Thanks.
12 Şub 2015 11:32 tarihinde "LorenzoBettini" <notifications@github.com>
yazdı:
